1. Write a Python (with numpy) program to center the data in each row in matrix  
  
A =  [2    4    6    8
      5    6    7    8 ]   

In [3]:
#importing the numpy module to use the array method and shape method
import numpy as np

# Creating a 2*2 matix 
A = np.array([[2,3,6,8],[5,6,7,8]])

#Printing the shape of the matrix
print(f"Shape of matrix is {A.shape}")

#Printing the Matrix A



print(A)

Shape of matrix is (2, 4)
[[2 3 6 8]
 [5 6 7 8]]


2. Write a Python (with numpy) program to solve the system of linear equations as 
following, print out the solution if it exists and print “no solution or infinite 
solution” for no solution/infinite solution:  
                                 3x1 + x2 + 4 x3= 3 
                                 9x1 + 4x2 +5 x3= 6  
                                 9x1 + 4x2 +6 x3= 9 

In [6]:
#Importing the numpy module
import numpy as np 

#Creating a numpy array to hold the linear equations
a = np.array([[3,1,4],[9,4,5],[9,4,6]])
b = np.array([3,6,9])
#calculate the determinent
det_val = np.linalg.det(a)
print(f"Determinent value:{round(det_val,2)}")

#Solution exisist only if determinent is not equal to zero
if(det_val != 0):
   #Using the linalg solve method to solve the equations
   x = np.linalg.solve(a,b)
   if (x.size != 0):
    print(f"Given matrix \n A = {a} \n Solution: {x}")
else:
   print("No solution")


Determinent value:3.0
Given matrix 
 A = [[3 1 4]
 [9 4 5]
 [9 4 6]] 
 Solution: [-9. 18.  3.]
